### ISSUE TITLE
Add support for modals

### ISSUE THREAD

**Issue by praveenperera** [infinitered/thesis-phoenix#167]
I was able to get modal editing working with some simple css

```css
#thesis-editor {
  z-index: 2000 !important;
}
```

However one problem I am having is that if, I make a content area that triggers the modal to open, I am unable to edit that content area without opening the modal.
